os: Visual Studio 2019
platform:
 - x86
 
init:
    - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

install:
  - C:\msys64\usr\bin\bash -lc "pacman --noconfirm -Syu"
  - C:\msys64\usr\bin\bash -lc "pacman --noconfirm -U https://repo.msys2.org/mingw/i686/mingw-w64-i686-libusb-1.0.23-1-any.pkg.tar.xz"
  - C:\msys64\usr\bin\bash -lc "pacman --noconfirm -Sy mingw-w64-i686-qt5"
  - set MINGW_PATH=C:\msys64\mingw32
  - set QTDIR=C:\msys64\mingw32\lib\cmake\Qt5
  - set PATH=C:\msys64\mingw32\lib;%PATH%

build_script:
  - git submodule update --init --recursive
  - C:\msys64\mingw32\bin\qmake.exe pp2trayer.pro
  - C:\msys64\mingw32\bin\mingw32-make.exe -j8

after_build:
- ps: |
    If (!(Test-Path -Path "distrib.zip")) {
      windeployqt --qmldir qml release\pp2trayer.exe --dir distrib
      7z a -y distrib.zip distrib
    }
    appveyor PushArtifact release\pp2trayer.exe
    appveyor PushArtifact distrib.zip

cache:
 - distrib.zip -> pp2trayer.pro
 - c:\msys.zip -> appveyor.yml
 
on_finish:
    - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
